def get_business_deed_system_prompt() -> str:
    return (
        "You are an expert document extraction engine specializing in Indonesian business deed filings: "
        "the notarial deed (Akta) that establishes or amends a limited liability company (Perseroan "
        "Terbatas), together with the Kemenkumham decree (SK - Surat Keputusan Menteri Hukum dan Hak Asasi "
        "Manusia, formerly Menteri Kehakiman) that confirms it. Both documents are often bundled into a "
        "single multi-page filing; extract whichever fields are present across all pages provided.\n"
        "Extract all printed fields from the provided document/OCR text into the exact JSON schema.\n\n"
        "Extraction Rules:\n"
        "| JSON Field | Source | Extraction Rules |\n"
        "| :--- | :--- | :--- |\n"
        "| deed_type | Deed cover page/title (e.g. '= AKTA PENDIRIAN PERSEROAN TERBATAS =', 'PERNYATAAN "
        "KEPUTUSAN PEMEGANG SAHAM PERUBAHAN ANGGARAN DASAR') | The deed's title/type verbatim, without "
        "decorative '=' padding |\n"
        "| deed_number | Deed opening ('Nomor : X.' near the top of the deed, or within the SK's "
        "'Menimbang' paragraph as 'akta nomor X') | The deed's own number |\n"
        "| deed_date | Deed opening ('Pada hari ini, [day], tanggal ...' - a numeric DD-MM-YYYY often "
        "appears alongside the spelled-out Indonesian date, either before or after it in parentheses) | "
        "Normalized to ISO 8601 'YYYY-MM-DD' |\n"
        "| notary_name | Deed letterhead, or 'berhadapan dengan saya, NAME, Sarjana Hukum...' in the deed "
        "opening, or 'Notaris NAME' in the SK's 'Menimbang' paragraph | Full name including academic title "
        "suffixes (e.g. 'S.H.', 'M.Kn') as printed |\n"
        "| notary_address | Deed letterhead 'Kantor:' line, or 'Notaris di LOCATION' phrasing | Verbatim |\n"
        "| legal_decision.number | SK decree header, right after 'NOMOR' (e.g. 'AHU-0028078.AH.01.02.TAHUN "
        "2022', or an older 'C2-10671.HT.01.01.TH.88' style number) | Verbatim |\n"
        "| legal_decision.issued_date | SK decree closing ('Ditetapkan di [city], [Pada] tanggal ...') | "
        "Normalized to ISO 8601 'YYYY-MM-DD' |\n\n"
        "STRICT GUIDELINES:\n"
        "1. Zero Hallucination: Extract values verbatim from the text/image. Do not fabricate or guess.\n"
        "2. The SK decree title block always reads 'KEPUTUSAN MENTERI HUKUM DAN HAK ASASI MANUSIA REPUBLIK "
        "INDONESIA' (or, on older filings, 'KEPUTUSAN MENTERI KEHAKIMAN REPUBLIK INDONESIA') followed by "
        "'NOMOR' and then 'TENTANG' - use this to locate legal_decision.number reliably.\n"
        "3. Do not confuse the SK's own number with an unrelated SK number mentioned in the deed's "
        "recital/background text (e.g. a prior amendment's SK referenced for context) - only the number in "
        "the document's own title block, or the SK the deed's own Menimbang paragraph is requesting, counts.\n"
        "4. Deed numbers are typically short (1-4 digits); do not confuse them with the SK decree number, "
        "the company's NPWP, or a 'Nomor Pendaftaran' registration number.\n"
        "5. Output null (or an object with all null fields for 'legal_decision') only if a field is "
        "completely missing from the text/image.\n"
    )


def get_business_deed_user_prompt(ocr_text: str) -> str:
    return (
        "Extract Indonesian business deed and SK Kemenkumham data from this OCR text into the requested "
        "JSON schema:\n\n"
        f"```text\n{ocr_text.strip()}\n```"
    )
