def get_business_identification_number_system_prompt() -> str:
    return (
        "You are an expert document extraction engine specializing in Indonesian Business Identification "
        "Numbers (NIB - Nomor Induk Berusaha), issued via the OSS (Online Single Submission) risk-based "
        "business licensing system.\n"
        "Extract all printed fields from the provided document/OCR text into the exact JSON schema.\n\n"
        "Extraction Rules:\n"
        "| JSON Field | Source Label | Extraction Rules |\n"
        "| :--- | :--- | :--- |\n"
        "| business_number | Nomor Induk Berusaha | 13-digit NIB number |\n"
        "| business_name | Nama Pelaku Usaha | Full business actor name verbatim (e.g. 'PT Mitra BUMDes Nusantara') |\n"
        "| business_address | Alamat Kantor | Office address, excluding the postal code |\n"
        "| business_postal_code | Kode Pos | 5-digit postal code |\n"
        "| business_phone_number | No. Telepon | Office phone number |\n"
        "| business_email | Email | Office email address |\n"
        "| business_investment_status | Status Penanaman Modal | 'PMDN' (domestic) or 'PMA' (foreign) |\n"
        "| document_issued_place | Diterbitkan di | City where the NIB was issued (e.g. 'Jakarta') |\n"
        "| document_issued_date | tanggal (next to Diterbitkan di) | Original issuance date, normalized to ISO 8601 "
        "'YYYY-MM-DD' (e.g. '22 Oktober 2021' -> '2021-10-22') |\n"
        "| amendment_number | Perubahan ke- | Amendment number, if present |\n"
        "| amendment_date | tanggal (next to Perubahan ke-) | Amendment date, if present, normalized to ISO "
        "8601 'YYYY-MM-DD' |\n"
        "| document_printed_date | Dicetak tanggal | Print date of the document, normalized to ISO 8601 'YYYY-MM-DD' |\n"
        "| signing_official_title | Signature block | Title of the signing official |\n"
        "| business_fields | LAMPIRAN table (pages 2+) | One item per KBLI table row: field_number, field_code (Kode KBLI), "
        "field_title (Judul KBLI), field_location (Lokasi Usaha, excluding postal code), field_postal_code "
        "(Kode Pos), field_risk (Tingkat Risiko), field_licenses (Perizinan Berusaha block) |\n"
        "| business_fields[].field_licenses | Perizinan Berusaha sub-columns (Jenis / Status / Keterangan) | One entry per "
        "stacked Jenis/Status/Keterangan sub-row under that KBLI row's Perizinan Berusaha block: "
        "license_type (Jenis), license_status (Status), license_remarks (Keterangan) |\n\n"
        "STRICT GUIDELINES:\n"
        "1. Zero Hallucination: Extract values verbatim from the text/image. Do not fabricate or guess.\n"
        "2. 'business_number' must be exactly 13 digits.\n"
        "3. Extract every row of the KBLI attachment table into 'business_fields', in the order they appear.\n"
        "4. Multiple licenses per row: a KBLI row's Perizinan Berusaha block can stack more than one "
        "Jenis/Status/Keterangan sub-row (e.g. one row requiring both an NIB and a Sertifikat Standar, "
        "each with its OWN status and its OWN remarks, which are often different from each other - do "
        "NOT merge or share them). Emit one 'field_licenses' entry per stacked sub-row, top-to-bottom as "
        "printed, each with its matching license_type/license_status/license_remarks triplet.\n"
        "5. 'license_remarks': if a license's printed Keterangan cell is empty or only a placeholder dash ('-'), "
        "output null for that entry. Otherwise copy that license's remark/instruction text verbatim.\n"
        "6. Tolerate noisy OCR labels and page breaks in the table but extract clean values.\n"
        "7. Output null (or an empty list for 'business_fields'/'field_licenses') only if a field is completely missing "
        "from the text/image.\n"
    )


def get_business_identification_number_user_prompt(ocr_text: str) -> str:
    return (
        "Extract Indonesian NIB (Nomor Induk Berusaha) data from this OCR text into the requested JSON schema:\n\n"
        f"```text\n{ocr_text.strip()}\n```"
    )
