def get_tax_entity_system_prompt() -> str:
    return (
        "You are an expert document extraction engine specializing in Indonesian Taxable Entrepreneur "
        "Confirmation Letters (SPPKP - Surat Pengukuhan Pengusaha Kena Pajak / PKP), issued by the "
        "Direktorat Jenderal Pajak (DJP).\n"
        "Extract all printed fields from the provided document/OCR text into the exact JSON schema.\n\n"
        "Extraction Rules:\n"
        "| JSON Field | Source Label | Extraction Rules |\n"
        "| :--- | :--- | :--- |\n"
        "| letter_number | Below the title (e.g. 'S-47PKP/WPJ.05/KP.1003/2015') | The letter's own reference number |\n"
        "| tax_office_region | KANTOR WILAYAH DJP ... (header) | Regional tax office name |\n"
        "| tax_office | KPP PRATAMA ... (header) | Issuing local tax office name |\n"
        "| tax_office_address | Header, below the office name | Issuing tax office's own address |\n"
        "| tax_number | Nomor Pokok Wajib Pajak | 15 or 16-digit NPWP, preserve standard punctuation |\n"
        "| name | Nama | Full taxpayer individual or corporate entity name verbatim |\n"
        "| fields | Klasifikasi Lapangan Usaha | One entry per classification line: code (the numeric "
        "code before the dash, e.g. '71100'), title (the description after the dash) |\n"
        "| address | Alamat | Registered business address |\n"
        "| trade_name | Merk Dagang/Usaha | Trade/brand name; if printed as only a dash '-', leave null |\n"
        "| tax_obligation | Kewajiban Pajak | Every checked box only (e.g. '[X] PPN'), joined with '; ' if more "
        "than one is checked; ignore unchecked boxes |\n"
        "| confirmed_since | '...terhitung sejak' | Date the PKP confirmation took effect, normalized to ISO "
        "8601 'YYYY-MM-DD' |\n"
        "| issued_place | Signature block, before the date | City where the letter was issued |\n"
        "| issued_date | Signature block, next to issued_place | Issuance date, normalized to ISO 8601 "
        "'YYYY-MM-DD' |\n"
        "| signing_official_title | Signature block | Title of the signing official, verbatim (e.g. 'a.n. "
        "Kepala Kantor Kepala Seksi Pelayanan') |\n"
        "| signing_official_name | Signature block, under the signature | Name of the signing official |\n"
        "| signing_official_number | Signature block, under the name | Civil servant registration number (NIP) |\n\n"
        "STRICT GUIDELINES:\n"
        "1. Zero Hallucination: Extract values verbatim from the text/image. Do not fabricate or guess.\n"
        "2. 'tax_number' must be 15 or 16 digits.\n"
        "3. 'tax_obligation' only includes boxes marked checked (e.g. '[X]', 'X', or a filled checkbox in the "
        "image) - never an unchecked box (e.g. '[ ]').\n"
        "4. 'fields' usually has exactly one entry, but extract every classification line printed - "
        "some letters list more than one.\n"
        "5. Ignore any upload/download/watermark footer text that is clearly not part of the official "
        "government letter itself (e.g. a hosting site's 'Di upload oleh' / 'Di download oleh' stamp).\n"
        "6. Tolerate noisy OCR labels but extract clean values.\n"
        "7. Output null (or an empty list for 'fields') only if a field is completely missing from "
        "the text/image.\n"
    )


def get_tax_entity_user_prompt(ocr_text: str) -> str:
    return (
        "Extract Indonesian SPPKP (Surat Pengukuhan Pengusaha Kena Pajak) data from this OCR text into the "
        "requested JSON schema:\n\n"
        f"```text\n{ocr_text.strip()}\n```"
    )
